package com.JD.Login.Hibernate.config;
// Generated Dec 30, 2014 2:39:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String userId;
     private String userPassword;
     private Integer userPriority;
     private String userEmail;
     private String userMob;
     private Date userLastAccountAccess;
     private String userAddress;
     private Date userDateOfAddition;
     private Date userTimeOfAddition;
     private String userLocation;
     private String userAddedByPersonName;
     private String userAddedWithRight;
     private String rawField1;
     private String rawField2;
     private String rawField3;
     private String rawField4;
     private String rawField5;
     private String rawField6;

    public Login() {
    }

    public Login(String userName, String userId, String userPassword, Integer userPriority, String userEmail, String userMob, Date userLastAccountAccess, String userAddress, Date userDateOfAddition, Date userTimeOfAddition, String userLocation, String userAddedByPersonName, String userAddedWithRight, String rawField1, String rawField2, String rawField3, String rawField4, String rawField5, String rawField6) {
       this.userName = userName;
       this.userId = userId;
       this.userPassword = userPassword;
       this.userPriority = userPriority;
       this.userEmail = userEmail;
       this.userMob = userMob;
       this.userLastAccountAccess = userLastAccountAccess;
       this.userAddress = userAddress;
       this.userDateOfAddition = userDateOfAddition;
       this.userTimeOfAddition = userTimeOfAddition;
       this.userLocation = userLocation;
       this.userAddedByPersonName = userAddedByPersonName;
       this.userAddedWithRight = userAddedWithRight;
       this.rawField1 = rawField1;
       this.rawField2 = rawField2;
       this.rawField3 = rawField3;
       this.rawField4 = rawField4;
       this.rawField5 = rawField5;
       this.rawField6 = rawField6;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public Integer getUserPriority() {
        return this.userPriority;
    }
    
    public void setUserPriority(Integer userPriority) {
        this.userPriority = userPriority;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserMob() {
        return this.userMob;
    }
    
    public void setUserMob(String userMob) {
        this.userMob = userMob;
    }
    public Date getUserLastAccountAccess() {
        return this.userLastAccountAccess;
    }
    
    public void setUserLastAccountAccess(Date userLastAccountAccess) {
        this.userLastAccountAccess = userLastAccountAccess;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public Date getUserDateOfAddition() {
        return this.userDateOfAddition;
    }
    
    public void setUserDateOfAddition(Date userDateOfAddition) {
        this.userDateOfAddition = userDateOfAddition;
    }
    public Date getUserTimeOfAddition() {
        return this.userTimeOfAddition;
    }
    
    public void setUserTimeOfAddition(Date userTimeOfAddition) {
        this.userTimeOfAddition = userTimeOfAddition;
    }
    public String getUserLocation() {
        return this.userLocation;
    }
    
    public void setUserLocation(String userLocation) {
        this.userLocation = userLocation;
    }
    public String getUserAddedByPersonName() {
        return this.userAddedByPersonName;
    }
    
    public void setUserAddedByPersonName(String userAddedByPersonName) {
        this.userAddedByPersonName = userAddedByPersonName;
    }
    public String getUserAddedWithRight() {
        return this.userAddedWithRight;
    }
    
    public void setUserAddedWithRight(String userAddedWithRight) {
        this.userAddedWithRight = userAddedWithRight;
    }
    public String getRawField1() {
        return this.rawField1;
    }
    
    public void setRawField1(String rawField1) {
        this.rawField1 = rawField1;
    }
    public String getRawField2() {
        return this.rawField2;
    }
    
    public void setRawField2(String rawField2) {
        this.rawField2 = rawField2;
    }
    public String getRawField3() {
        return this.rawField3;
    }
    
    public void setRawField3(String rawField3) {
        this.rawField3 = rawField3;
    }
    public String getRawField4() {
        return this.rawField4;
    }
    
    public void setRawField4(String rawField4) {
        this.rawField4 = rawField4;
    }
    public String getRawField5() {
        return this.rawField5;
    }
    
    public void setRawField5(String rawField5) {
        this.rawField5 = rawField5;
    }
    public String getRawField6() {
        return this.rawField6;
    }
    
    public void setRawField6(String rawField6) {
        this.rawField6 = rawField6;
    }




}


