/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.JD.Login.Form;

import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Yogesh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        restore_Lable.setVisible(false);
        message_Lable.setVisible(false);
        saveBK_Lable.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_ID = new javax.swing.JTextField();
        user_Password = new javax.swing.JPasswordField();
        reset_Button = new javax.swing.JButton();
        login_Button = new javax.swing.JButton();
        ad_CheacBox = new javax.swing.JCheckBox();
        restore_Lable = new javax.swing.JLabel();
        message_Lable = new javax.swing.JLabel();
        saveBK_Lable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LogIn Window");
        setBounds(new java.awt.Rectangle(500, 100, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Login/Form/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 376, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Login/Form/statonary2.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("* User ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("* Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 179, -1, -1));

        user_ID.setText("Administrator");
        getContentPane().add(user_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 138, 188, -1));

        user_Password.setText("Administrator");
        getContentPane().add(user_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 180, 188, -1));

        reset_Button.setText("Reset");
        reset_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(reset_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 218, 90, -1));

        login_Button.setText("Login");
        login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 218, 88, -1));

        ad_CheacBox.setText("Show Advance Option");
        ad_CheacBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_CheacBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ad_CheacBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 259, -1, -1));

        restore_Lable.setForeground(new java.awt.Color(0, 0, 255));
        restore_Lable.setText(" Click Here To Restore Master BackUp ! ");
        restore_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        restore_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(restore_Lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 289, -1, -1));

        message_Lable.setText(" If You Plan To Formate Your System !");
        getContentPane().add(message_Lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 323, -1, -1));

        saveBK_Lable.setForeground(new java.awt.Color(0, 0, 255));
        saveBK_Lable.setText(" Click Here To Save Master BackUp !     ");
        saveBK_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saveBK_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(saveBK_Lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 355, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_ButtonActionPerformed
        // TODO add your handling code here:        
        reset();
    }//GEN-LAST:event_reset_ButtonActionPerformed

    private void login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_ButtonActionPerformed
        // TODO add your handling code here:

        String userId = user_ID.getText();
        String password = user_Password.getText();

        Session session = com.JD.StaticData.Static_DATA.init_SessionFactory.openSession();

        Criteria cr = session.createCriteria(com.JD.Login.Hibernate.config.Login.class);
        cr.add(Restrictions.eq("userId", userId));
        cr.add(Restrictions.eq("userPassword", password));
        List results = cr.list();

        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: User Id Or Password Is Wrong..");
            reset();
        } else {
            for (Object object : results) {
                com.JD.Login.Hibernate.config.Login l = (com.JD.Login.Hibernate.config.Login) object;
                com.JD.StaticData.Static_DATA.logIn_Priority = l.getUserPriority();
                com.JD.StaticData.Static_DATA.logIn_UserName = l.getUserName();
                com.JD.StaticData.Static_DATA.logIn_Right = l.getUserAddedWithRight();
                new com.JD.Home.JD_Home().setVisible(true);
            }

            dispose();
        }
        session.close();
    }//GEN-LAST:event_login_ButtonActionPerformed

    private void ad_CheacBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_CheacBoxActionPerformed
        // TODO add your handling code here:
        if (ad_CheacBox.isSelected()) {
            restore_Lable.setVisible(true);
            message_Lable.setVisible(true);
            saveBK_Lable.setVisible(true);
        } else {
            restore_Lable.setVisible(false);
            message_Lable.setVisible(false);
            saveBK_Lable.setVisible(false);
        }
    }//GEN-LAST:event_ad_CheacBoxActionPerformed

    void reset() {
        user_ID.setText("");
        user_Password.setText("");
        restore_Lable.setVisible(false);
        message_Lable.setVisible(false);
        saveBK_Lable.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ad_CheacBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_Button;
    private javax.swing.JLabel message_Lable;
    private javax.swing.JButton reset_Button;
    private javax.swing.JLabel restore_Lable;
    private javax.swing.JLabel saveBK_Lable;
    private javax.swing.JTextField user_ID;
    private javax.swing.JPasswordField user_Password;
    // End of variables declaration//GEN-END:variables
}
