package com.JD.InitData.Hibernate.config;
// Generated Dec 30, 2014 2:37:59 PM by Hibernate Tools 3.2.1.GA



/**
 * Initdata generated by hbm2java
 */
public class Initdata  implements java.io.Serializable {


     private Integer id;
     private String location;
     private String prSrNo;
     private Integer srNo;
     private String registrationNumber;
     private String rawField1;
     private String rawField2;
     private String rawField3;
     private String rawField4;
     private String rawField5;
     private Integer rawField6;
     private Integer rawField7;
     private Integer rawField8;
     private Integer rawField9;
     private Integer rawField10;

    public Initdata() {
    }

    public Initdata(String location, String prSrNo, Integer srNo, String registrationNumber, String rawField1, String rawField2, String rawField3, String rawField4, String rawField5, Integer rawField6, Integer rawField7, Integer rawField8, Integer rawField9, Integer rawField10) {
       this.location = location;
       this.prSrNo = prSrNo;
       this.srNo = srNo;
       this.registrationNumber = registrationNumber;
       this.rawField1 = rawField1;
       this.rawField2 = rawField2;
       this.rawField3 = rawField3;
       this.rawField4 = rawField4;
       this.rawField5 = rawField5;
       this.rawField6 = rawField6;
       this.rawField7 = rawField7;
       this.rawField8 = rawField8;
       this.rawField9 = rawField9;
       this.rawField10 = rawField10;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getPrSrNo() {
        return this.prSrNo;
    }
    
    public void setPrSrNo(String prSrNo) {
        this.prSrNo = prSrNo;
    }
    public Integer getSrNo() {
        return this.srNo;
    }
    
    public void setSrNo(Integer srNo) {
        this.srNo = srNo;
    }
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }
    public String getRawField1() {
        return this.rawField1;
    }
    
    public void setRawField1(String rawField1) {
        this.rawField1 = rawField1;
    }
    public String getRawField2() {
        return this.rawField2;
    }
    
    public void setRawField2(String rawField2) {
        this.rawField2 = rawField2;
    }
    public String getRawField3() {
        return this.rawField3;
    }
    
    public void setRawField3(String rawField3) {
        this.rawField3 = rawField3;
    }
    public String getRawField4() {
        return this.rawField4;
    }
    
    public void setRawField4(String rawField4) {
        this.rawField4 = rawField4;
    }
    public String getRawField5() {
        return this.rawField5;
    }
    
    public void setRawField5(String rawField5) {
        this.rawField5 = rawField5;
    }
    public Integer getRawField6() {
        return this.rawField6;
    }
    
    public void setRawField6(Integer rawField6) {
        this.rawField6 = rawField6;
    }
    public Integer getRawField7() {
        return this.rawField7;
    }
    
    public void setRawField7(Integer rawField7) {
        this.rawField7 = rawField7;
    }
    public Integer getRawField8() {
        return this.rawField8;
    }
    
    public void setRawField8(Integer rawField8) {
        this.rawField8 = rawField8;
    }
    public Integer getRawField9() {
        return this.rawField9;
    }
    
    public void setRawField9(Integer rawField9) {
        this.rawField9 = rawField9;
    }
    public Integer getRawField10() {
        return this.rawField10;
    }
    
    public void setRawField10(Integer rawField10) {
        this.rawField10 = rawField10;
    }




}


