/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.JD.Home;

import com.JD.DailyReports.Report_Home;
import com.JD.Diesel.Forms.Diesel_Home;
import com.JD.Help.Help_Form;
import com.JD.Machine.StartStop.MachineStartStop_Home;
import com.JD.Notification.Form.Notification;
import com.JD.PrintReceiptDM.Form.DM_Home;
import com.JD.Search.Search_Home;
import com.JD.Setting.Setting_Home;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yogesh
 */
public class JD_Home extends javax.swing.JFrame {

    /**
     * Creates new form JD_Home
     */
    String hideImageName = "Hide.jpg";
    URL hideImageNameURL = getClass().getResource(hideImageName);
    Toolkit hideImageNametk = Toolkit.getDefaultToolkit();
    Image hideImage = hideImageNametk.getImage(hideImageNameURL);
    ImageIcon hideICO = new ImageIcon(hideImage);
    String unHideImageName = "Show.jpg";
    URL unHideImageNameURL = getClass().getResource(unHideImageName);
    Toolkit unHideImageNametk = Toolkit.getDefaultToolkit();
    Image unHideImage = unHideImageNametk.getImage(unHideImageNameURL);
    ImageIcon unHideICO = new ImageIcon(unHideImage);
    //-- User Name--//
    String userNameTemp = com.JD.StaticData.Static_DATA.logIn_UserName;
    String dataTemp[] = userNameTemp.split(" ");
    //-- User Name--//
    //------ Default Width and Height of parentComponentHolder_Panel------//
    int width = 00;
    int height = 00;
    //------ Default Width and Height of parentComponentHolder_Panel------//
    //---- All Menu Entry ------//
    com.JD.Master.Forms.MasterHome masterHome = new com.JD.Master.Forms.MasterHome();
    com.JD.PrintReceiptDM.Form.DM_Home dM_Home = new DM_Home();
    com.JD.Diesel.Forms.Diesel_Home diesel_Home = new Diesel_Home();
    com.JD.Notification.Form.Notification notification = new Notification();
    com.JD.Search.Search_Home search_Home = new Search_Home();
    com.JD.DailyReports.Report_Home report_Home = new Report_Home();
    com.JD.Setting.Setting_Home setting_Home = new Setting_Home();
    com.JD.Help.Help_Form help_Form = new Help_Form();
    com.JD.Machine.StartStop.MachineStartStop_Home machineStartStop_Home;
    //---- All Menu Entry ------//

    public JD_Home() {
        initComponents();
        com.JD.StaticData.Static_DATA.fuelQuantity_Lable = fuelQuantity_Lable;
        com.JD.StaticData.Static_DATA.running_Lable=running_Lable;
        com.JD.StaticData.Static_DATA.purchaseDiesel_Form.setCurrentDieselLog(0.0);
        //------ Default Width and Height of parentComponentHolder_Panel------//
        width = parentComponentHolder_Panel.getWidth();
        height = parentComponentHolder_Panel.getHeight();
        //------ Default Width and Height of parentComponentHolder_Panel------//
        user_Lable.setText("Welcome " + dataTemp[0] + " ");
        defultPanel();     
        machineStartStop_Home=new MachineStartStop_Home();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        hideUnhide_Lable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentWindow_Labe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_Lable = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logout_Lable = new javax.swing.JLabel();
        menuItem_Panel = new javax.swing.JPanel();
        master_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dm_Button = new javax.swing.JButton();
        diesel_Button = new javax.swing.JButton();
        notification_Button = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        startStop_Button = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        search_Button = new javax.swing.JButton();
        report_Button = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        setting_Button = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        parentComponentHolder_Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        notification_Lable = new javax.swing.JLabel();
        fuelQuantity_Lable = new javax.swing.JLabel();
        running_Lable = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        notification_ShortCut = new javax.swing.JMenuItem();
        master_ShortCut = new javax.swing.JMenuItem();
        dm_ShortCut = new javax.swing.JMenuItem();
        diesel_ShortCut = new javax.swing.JMenuItem();
        startStop_ShortCut = new javax.swing.JMenuItem();
        serch_ShortCut = new javax.swing.JMenuItem();
        dailyReport_ShortCut = new javax.swing.JMenuItem();
        scanner_ShortCut = new javax.swing.JMenuItem();
        setting_ShortCut = new javax.swing.JMenuItem();
        help_Menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crusher Manager");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(255, 51, 255));
        jToolBar1.setRollover(true);

        hideUnhide_Lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/Hide.jpg"))); // NOI18N
        hideUnhide_Lable.setText(" Hide Menu                            ");
        hideUnhide_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        hideUnhide_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hideUnhide_Lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideUnhide_LableMouseClicked(evt);
            }
        });
        jToolBar1.add(hideUnhide_Lable);

        jLabel2.setText("      ");
        jToolBar1.add(jLabel2);

        currentWindow_Labe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/down.jpg"))); // NOI18N
        currentWindow_Labe.setText("Current Page You Are Viewing is ");
        currentWindow_Labe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jToolBar1.add(currentWindow_Labe);

        jLabel3.setText("                                                                                                                                                                                                                   ");
        jToolBar1.add(jLabel3);

        user_Lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/user.png"))); // NOI18N
        user_Lable.setText(" Welcome Yogesh Paisode ");
        user_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jToolBar1.add(user_Lable);

        jLabel4.setText("             ");
        jToolBar1.add(jLabel4);

        logout_Lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/logout.jpg"))); // NOI18N
        logout_Lable.setText(" Logout ");
        logout_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        logout_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_Lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_LableMouseClicked(evt);
            }
        });
        jToolBar1.add(logout_Lable);

        menuItem_Panel.setBackground(new java.awt.Color(51, 102, 255));
        menuItem_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        master_Button.setText("Master :                         F2");
        master_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                master_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Login/Form/statonary2.gif"))); // NOI18N

        dm_Button.setText("Print Receipt/DM :        F3 ");
        dm_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dm_ButtonActionPerformed(evt);
            }
        });

        diesel_Button.setText("Diesel :                           F4 ");
        diesel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diesel_ButtonActionPerformed(evt);
            }
        });

        notification_Button.setText("Notification :                 F1");
        notification_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notification_ButtonActionPerformed(evt);
            }
        });

        startStop_Button.setText("Machine Start/Stop :    F5  ");
        startStop_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStop_ButtonActionPerformed(evt);
            }
        });

        search_Button.setText("Search :                          F6");
        search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_ButtonActionPerformed(evt);
            }
        });

        report_Button.setText("Daily Report :                 F7");
        report_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_ButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Scanner :                        F8");

        setting_Button.setText("Setting :                         F9");
        setting_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setting_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuItem_PanelLayout = new javax.swing.GroupLayout(menuItem_Panel);
        menuItem_Panel.setLayout(menuItem_PanelLayout);
        menuItem_PanelLayout.setHorizontalGroup(
            menuItem_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(notification_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(master_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dm_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(diesel_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(startStop_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addComponent(search_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(report_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator5)
            .addComponent(setting_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator6)
        );
        menuItem_PanelLayout.setVerticalGroup(
            menuItem_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuItem_PanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notification_Button)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(master_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dm_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diesel_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startStop_Button)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_Button)
                .addGap(18, 18, 18)
                .addComponent(report_Button)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setting_Button)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        parentComponentHolder_Panel.setBackground(new java.awt.Color(255, 102, 51));
        parentComponentHolder_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        parentComponentHolder_Panel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                parentComponentHolder_PanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout parentComponentHolder_PanelLayout = new javax.swing.GroupLayout(parentComponentHolder_Panel);
        parentComponentHolder_Panel.setLayout(parentComponentHolder_PanelLayout);
        parentComponentHolder_PanelLayout.setHorizontalGroup(
            parentComponentHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1079, Short.MAX_VALUE)
        );
        parentComponentHolder_PanelLayout.setVerticalGroup(
            parentComponentHolder_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Login/Form/statonary2.gif"))); // NOI18N

        notification_Lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/notification.png"))); // NOI18N
        notification_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        notification_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notification_Lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notification_LableMouseClicked(evt);
            }
        });

        fuelQuantity_Lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/purched.png"))); // NOI18N
        fuelQuantity_Lable.setText(" +134.99 LTR ");
        fuelQuantity_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        fuelQuantity_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fuelQuantity_Lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fuelQuantity_LableMouseClicked(evt);
            }
        });

        running_Lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/running.png"))); // NOI18N
        running_Lable.setText("  + 023 Machine Running");
        running_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        running_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        running_Lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                running_LableMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/servi.png"))); // NOI18N
        jLabel6.setText("  + 056 Machine Ready For Servicing   ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/reay.png"))); // NOI18N
        jLabel7.setText("   + 076 Machine Close To Servicing   ");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(notification_Lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fuelQuantity_Lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(running_Lable, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fuelQuantity_Lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notification_Lable)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(running_Lable)
                            .addComponent(jLabel6)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7))
        );

        jMenu1.setText("File");

        notification_ShortCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        notification_ShortCut.setText("Notification");
        notification_ShortCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notification_ShortCutActionPerformed(evt);
            }
        });
        jMenu1.add(notification_ShortCut);

        master_ShortCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        master_ShortCut.setText("Master");
        master_ShortCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                master_ShortCutActionPerformed(evt);
            }
        });
        jMenu1.add(master_ShortCut);

        dm_ShortCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        dm_ShortCut.setText("Print Receipt/DM ");
        dm_ShortCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dm_ShortCutActionPerformed(evt);
            }
        });
        jMenu1.add(dm_ShortCut);

        diesel_ShortCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        diesel_ShortCut.setText("Diesel");
        diesel_ShortCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diesel_ShortCutActionPerformed(evt);
            }
        });
        jMenu1.add(diesel_ShortCut);

        startStop_ShortCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        startStop_ShortCut.setText("Machine Start/Stop");
        startStop_ShortCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStop_ShortCutActionPerformed(evt);
            }
        });
        jMenu1.add(startStop_ShortCut);

        serch_ShortCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        serch_ShortCut.setText("Search");
        serch_ShortCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serch_ShortCutActionPerformed(evt);
            }
        });
        jMenu1.add(serch_ShortCut);

        dailyReport_ShortCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        dailyReport_ShortCut.setText("Daily Report");
        dailyReport_ShortCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyReport_ShortCutActionPerformed(evt);
            }
        });
        jMenu1.add(dailyReport_ShortCut);

        scanner_ShortCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        scanner_ShortCut.setText("Scanner");
        jMenu1.add(scanner_ShortCut);

        setting_ShortCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        setting_ShortCut.setText("Setting");
        setting_ShortCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setting_ShortCutActionPerformed(evt);
            }
        });
        jMenu1.add(setting_ShortCut);

        jMenuBar1.add(jMenu1);

        help_Menu.setText("Help");
        help_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                help_MenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(help_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1273, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuItem_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parentComponentHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuItem_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(parentComponentHolder_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void master_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_master_ButtonActionPerformed
        // TODO add your handling code here:  
        masterSet();
    }//GEN-LAST:event_master_ButtonActionPerformed
    void masterSet() {
        masterHome.masterHome_TabbedPane.setBounds(0, 0, width, height);
        parentComponentHolder_Panel.removeAll();
        parentComponentHolder_Panel.add(masterHome.getMasterHome_TabbedPane());
        parentComponentHolder_Panel.repaint();
        parentComponentHolder_Panel.revalidate();
        currentWindow_Labe.setText(" Master Window ");
        com.JD.StaticData.Static_DATA.webCam_Panel.add(com.JD.StaticData.Static_DATA.webPanel);
    }
    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized
    
    private void hideUnhide_LableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideUnhide_LableMouseClicked
        // TODO add your handling code here:

        if (hideUnhide_Lable.getText().equals(" Hide Menu                            ")) {
            menuItem_Panel.setVisible(false);
            hideUnhide_Lable.setText(" UnHide Menu                            ");
            hideUnhide_Lable.setIcon(unHideICO);
        } else {
            menuItem_Panel.setVisible(true);
            hideUnhide_Lable.setText(" Hide Menu                            ");
            hideUnhide_Lable.setIcon(hideICO);
        }
    }//GEN-LAST:event_hideUnhide_LableMouseClicked
    
    private void parentComponentHolder_PanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_parentComponentHolder_PanelComponentResized
        // TODO add your handling code here:
        //------ Default Width and Height of parentComponentHolder_Panel------//
        width = parentComponentHolder_Panel.getWidth();
        height = parentComponentHolder_Panel.getHeight();
        //------ Default Width and Height of parentComponentHolder_Panel------//
        masterHome.masterHome_TabbedPane.setBounds(0, 0, width, height);
        dM_Home.DM_Home_TabbedPane.setBounds(0, 0, width, height);
        diesel_Home.dieselHome_TabbedPanel.setBounds(0, 0, width, height);
        search_Home.search_TabbedPanel.setBounds(0, 0, width, height);
        report_Home.report_TabbedPanel.setBounds(0, 0, width, height);
        setting_Home.Setting_Home_TabbedPane.setBounds(0, 0, width, height);
        machineStartStop_Home.machineStartStop_TabbedPanel.setBounds(0, 0, width, height);
        
    }//GEN-LAST:event_parentComponentHolder_PanelComponentResized
    
    private void dm_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dm_ButtonActionPerformed
        // TODO add your handling code here:
        dmSet();
        
    }//GEN-LAST:event_dm_ButtonActionPerformed
    void dmSet() {
        parentComponentHolder_Panel.removeAll();
        parentComponentHolder_Panel.add(dM_Home.DM_Home_TabbedPane);
        parentComponentHolder_Panel.repaint();
        parentComponentHolder_Panel.revalidate();
        currentWindow_Labe.setText(" Print Receipt/DM Window ");
        com.JD.StaticData.Static_DATA.webCam_Panel_Dm.add(com.JD.StaticData.Static_DATA.webPanel);
    }
    private void diesel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diesel_ButtonActionPerformed
        // TODO add your handling code here:        
        dieselPanel();
    }//GEN-LAST:event_diesel_ButtonActionPerformed
    void dieselPanel() {
        parentComponentHolder_Panel.removeAll();
        parentComponentHolder_Panel.add(diesel_Home.dieselHome_TabbedPanel);
        parentComponentHolder_Panel.repaint();
        parentComponentHolder_Panel.revalidate();
        currentWindow_Labe.setText(" Diesel Window ");
    }
    private void notification_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notification_ButtonActionPerformed
        // TODO add your handling code here:
        defultPanel();
    }//GEN-LAST:event_notification_ButtonActionPerformed
    
    private void notification_LableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notification_LableMouseClicked
        // TODO add your handling code here:
        defultPanel();
    }//GEN-LAST:event_notification_LableMouseClicked
    
    private void fuelQuantity_LableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fuelQuantity_LableMouseClicked
        // TODO add your handling code here:
        dieselPanel();
    }//GEN-LAST:event_fuelQuantity_LableMouseClicked
    
    private void search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_ButtonActionPerformed
        // TODO add your handling code here:
        searchSet();
    }//GEN-LAST:event_search_ButtonActionPerformed
    void searchSet() {
        parentComponentHolder_Panel.removeAll();
        parentComponentHolder_Panel.add(search_Home.search_TabbedPanel);
        parentComponentHolder_Panel.repaint();
        parentComponentHolder_Panel.revalidate();
        currentWindow_Labe.setText(" Search Window ");
    }
    private void report_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_ButtonActionPerformed
        // TODO add your handling code here:
        reportSet();
    }//GEN-LAST:event_report_ButtonActionPerformed
    void reportSet() {
        parentComponentHolder_Panel.removeAll();
        parentComponentHolder_Panel.add(report_Home.report_TabbedPanel);
        parentComponentHolder_Panel.repaint();
        parentComponentHolder_Panel.revalidate();
        currentWindow_Labe.setText(" Daily Report Window ");
    }
    private void setting_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setting_ButtonActionPerformed
        // TODO add your handling code here:       
        settingSet();
    }//GEN-LAST:event_setting_ButtonActionPerformed
    void settingSet() {
        parentComponentHolder_Panel.removeAll();
        parentComponentHolder_Panel.add(setting_Home.Setting_Home_TabbedPane);
        parentComponentHolder_Panel.repaint();
        parentComponentHolder_Panel.revalidate();
        currentWindow_Labe.setText(" Setting Window ");
    }
    private void notification_ShortCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notification_ShortCutActionPerformed
        // TODO add your handling code here:
        defultPanel();
    }//GEN-LAST:event_notification_ShortCutActionPerformed
    
    private void master_ShortCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_master_ShortCutActionPerformed
        // TODO add your handling code here:
        masterSet();
    }//GEN-LAST:event_master_ShortCutActionPerformed
    
    private void dm_ShortCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dm_ShortCutActionPerformed
        // TODO add your handling code here:
        dmSet();
    }//GEN-LAST:event_dm_ShortCutActionPerformed
    
    private void diesel_ShortCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diesel_ShortCutActionPerformed
        // TODO add your handling code here:
        dieselPanel();
    }//GEN-LAST:event_diesel_ShortCutActionPerformed
    void startStop() {
        parentComponentHolder_Panel.removeAll();
        parentComponentHolder_Panel.add(machineStartStop_Home.machineStartStop_TabbedPanel);
        parentComponentHolder_Panel.repaint();
        parentComponentHolder_Panel.revalidate();
        currentWindow_Labe.setText(" Machine Start Stop Log Window ");
    }
    private void startStop_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStop_ButtonActionPerformed
        // TODO add your handling code here:
        startStop();
    }//GEN-LAST:event_startStop_ButtonActionPerformed
    
    private void serch_ShortCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serch_ShortCutActionPerformed
        // TODO add your handling code here:
        searchSet();
    }//GEN-LAST:event_serch_ShortCutActionPerformed
    
    private void dailyReport_ShortCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyReport_ShortCutActionPerformed
        // TODO add your handling code here:
        reportSet();
    }//GEN-LAST:event_dailyReport_ShortCutActionPerformed
    
    private void setting_ShortCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setting_ShortCutActionPerformed
        // TODO add your handling code here:
        settingSet();
    }//GEN-LAST:event_setting_ShortCutActionPerformed
    
    private void help_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help_MenuMouseClicked
        // TODO add your handling code here:
        parentComponentHolder_Panel.removeAll();
        parentComponentHolder_Panel.add(help_Form.help_Panel);
        parentComponentHolder_Panel.repaint();
        parentComponentHolder_Panel.revalidate();
        currentWindow_Labe.setText(" Help Window ");
    }//GEN-LAST:event_help_MenuMouseClicked
    
    private void logout_LableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_LableMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_logout_LableMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Are You Sure..");
    }//GEN-LAST:event_formWindowClosing

    private void startStop_ShortCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStop_ShortCutActionPerformed
        // TODO add your handling code here:
        startStop();
    }//GEN-LAST:event_startStop_ShortCutActionPerformed

    private void running_LableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_running_LableMouseClicked
        // TODO add your handling code here:
         startStop();
    }//GEN-LAST:event_running_LableMouseClicked
    void defultPanel() {
        parentComponentHolder_Panel.removeAll();
        parentComponentHolder_Panel.add(notification.notification_Panel);
        parentComponentHolder_Panel.repaint();
        parentComponentHolder_Panel.revalidate();
        currentWindow_Labe.setText(" Notification Window ");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new JD_Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentWindow_Labe;
    private javax.swing.JMenuItem dailyReport_ShortCut;
    private javax.swing.JButton diesel_Button;
    private javax.swing.JMenuItem diesel_ShortCut;
    private javax.swing.JButton dm_Button;
    private javax.swing.JMenuItem dm_ShortCut;
    private javax.swing.JLabel fuelQuantity_Lable;
    private javax.swing.JMenu help_Menu;
    private javax.swing.JLabel hideUnhide_Lable;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel logout_Lable;
    private javax.swing.JButton master_Button;
    private javax.swing.JMenuItem master_ShortCut;
    private javax.swing.JPanel menuItem_Panel;
    private javax.swing.JButton notification_Button;
    private javax.swing.JLabel notification_Lable;
    private javax.swing.JMenuItem notification_ShortCut;
    private javax.swing.JPanel parentComponentHolder_Panel;
    private javax.swing.JButton report_Button;
    private javax.swing.JLabel running_Lable;
    private javax.swing.JMenuItem scanner_ShortCut;
    private javax.swing.JButton search_Button;
    private javax.swing.JMenuItem serch_ShortCut;
    private javax.swing.JButton setting_Button;
    private javax.swing.JMenuItem setting_ShortCut;
    private javax.swing.JButton startStop_Button;
    private javax.swing.JMenuItem startStop_ShortCut;
    private javax.swing.JLabel user_Lable;
    // End of variables declaration//GEN-END:variables
}
