package com.JD.Master.Hibernate.config;
// Generated Jan 2, 2015 12:41:03 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Partymaster generated by hbm2java
 */
public class Partymaster  implements java.io.Serializable {


     private Integer id;
     private String partyName;
     private String partyAddress;
     private String partyCity;
     private String partyPhone;
     private String partyMobile;
     private String partyEmail;
     private Date partyDateOfAddition;
     private Date partyTimeOfAddition;
     private String partyLocation;
     private String partyAddedByPersonName;
     private String partyAddedWithRight;
     private String rawField1;
     private String rawField2;
     private String rawField3;
     private String rawField4;
     private String rawField5;
     private String rawField6;

    public Partymaster() {
    }

    public Partymaster(String partyName, String partyAddress, String partyCity, String partyPhone, String partyMobile, String partyEmail, Date partyDateOfAddition, Date partyTimeOfAddition, String partyLocation, String partyAddedByPersonName, String partyAddedWithRight, String rawField1, String rawField2, String rawField3, String rawField4, String rawField5, String rawField6) {
       this.partyName = partyName;
       this.partyAddress = partyAddress;
       this.partyCity = partyCity;
       this.partyPhone = partyPhone;
       this.partyMobile = partyMobile;
       this.partyEmail = partyEmail;
       this.partyDateOfAddition = partyDateOfAddition;
       this.partyTimeOfAddition = partyTimeOfAddition;
       this.partyLocation = partyLocation;
       this.partyAddedByPersonName = partyAddedByPersonName;
       this.partyAddedWithRight = partyAddedWithRight;
       this.rawField1 = rawField1;
       this.rawField2 = rawField2;
       this.rawField3 = rawField3;
       this.rawField4 = rawField4;
       this.rawField5 = rawField5;
       this.rawField6 = rawField6;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPartyName() {
        return this.partyName;
    }
    
    public void setPartyName(String partyName) {
        this.partyName = partyName;
    }
    public String getPartyAddress() {
        return this.partyAddress;
    }
    
    public void setPartyAddress(String partyAddress) {
        this.partyAddress = partyAddress;
    }
    public String getPartyCity() {
        return this.partyCity;
    }
    
    public void setPartyCity(String partyCity) {
        this.partyCity = partyCity;
    }
    public String getPartyPhone() {
        return this.partyPhone;
    }
    
    public void setPartyPhone(String partyPhone) {
        this.partyPhone = partyPhone;
    }
    public String getPartyMobile() {
        return this.partyMobile;
    }
    
    public void setPartyMobile(String partyMobile) {
        this.partyMobile = partyMobile;
    }
    public String getPartyEmail() {
        return this.partyEmail;
    }
    
    public void setPartyEmail(String partyEmail) {
        this.partyEmail = partyEmail;
    }
    public Date getPartyDateOfAddition() {
        return this.partyDateOfAddition;
    }
    
    public void setPartyDateOfAddition(Date partyDateOfAddition) {
        this.partyDateOfAddition = partyDateOfAddition;
    }
    public Date getPartyTimeOfAddition() {
        return this.partyTimeOfAddition;
    }
    
    public void setPartyTimeOfAddition(Date partyTimeOfAddition) {
        this.partyTimeOfAddition = partyTimeOfAddition;
    }
    public String getPartyLocation() {
        return this.partyLocation;
    }
    
    public void setPartyLocation(String partyLocation) {
        this.partyLocation = partyLocation;
    }
    public String getPartyAddedByPersonName() {
        return this.partyAddedByPersonName;
    }
    
    public void setPartyAddedByPersonName(String partyAddedByPersonName) {
        this.partyAddedByPersonName = partyAddedByPersonName;
    }
    public String getPartyAddedWithRight() {
        return this.partyAddedWithRight;
    }
    
    public void setPartyAddedWithRight(String partyAddedWithRight) {
        this.partyAddedWithRight = partyAddedWithRight;
    }
    public String getRawField1() {
        return this.rawField1;
    }
    
    public void setRawField1(String rawField1) {
        this.rawField1 = rawField1;
    }
    public String getRawField2() {
        return this.rawField2;
    }
    
    public void setRawField2(String rawField2) {
        this.rawField2 = rawField2;
    }
    public String getRawField3() {
        return this.rawField3;
    }
    
    public void setRawField3(String rawField3) {
        this.rawField3 = rawField3;
    }
    public String getRawField4() {
        return this.rawField4;
    }
    
    public void setRawField4(String rawField4) {
        this.rawField4 = rawField4;
    }
    public String getRawField5() {
        return this.rawField5;
    }
    
    public void setRawField5(String rawField5) {
        this.rawField5 = rawField5;
    }
    public String getRawField6() {
        return this.rawField6;
    }
    
    public void setRawField6(String rawField6) {
        this.rawField6 = rawField6;
    }




}


