package com.JD.Master.Hibernate.config;
// Generated Jan 2, 2015 1:15:02 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Drivermaster generated by hbm2java
 */
public class Drivermaster  implements java.io.Serializable {


     private Integer id;
     private String driverPartyLink;
     private String driverName;
     private String driverAddress;
     private String driverMobile;
     private String driverBloodGroup;
     private Date driverDateOfJoining;
     private String driverPic;
     private Date driverDateOfAddition;
     private Date driverTimeOfAddition;
     private String driverLocation;
     private String driverAddedByPersonName;
     private String driverAddedWithRight;
     private String rawField1;
     private String rawField2;
     private String rawField3;
     private String rawField4;
     private String rawField5;
     private String rawField6;

    public Drivermaster() {
    }

    public Drivermaster(String driverPartyLink, String driverName, String driverAddress, String driverMobile, String driverBloodGroup, Date driverDateOfJoining, String driverPic, Date driverDateOfAddition, Date driverTimeOfAddition, String driverLocation, String driverAddedByPersonName, String driverAddedWithRight, String rawField1, String rawField2, String rawField3, String rawField4, String rawField5, String rawField6) {
       this.driverPartyLink = driverPartyLink;
       this.driverName = driverName;
       this.driverAddress = driverAddress;
       this.driverMobile = driverMobile;
       this.driverBloodGroup = driverBloodGroup;
       this.driverDateOfJoining = driverDateOfJoining;
       this.driverPic = driverPic;
       this.driverDateOfAddition = driverDateOfAddition;
       this.driverTimeOfAddition = driverTimeOfAddition;
       this.driverLocation = driverLocation;
       this.driverAddedByPersonName = driverAddedByPersonName;
       this.driverAddedWithRight = driverAddedWithRight;
       this.rawField1 = rawField1;
       this.rawField2 = rawField2;
       this.rawField3 = rawField3;
       this.rawField4 = rawField4;
       this.rawField5 = rawField5;
       this.rawField6 = rawField6;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDriverPartyLink() {
        return this.driverPartyLink;
    }
    
    public void setDriverPartyLink(String driverPartyLink) {
        this.driverPartyLink = driverPartyLink;
    }
    public String getDriverName() {
        return this.driverName;
    }
    
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }
    public String getDriverAddress() {
        return this.driverAddress;
    }
    
    public void setDriverAddress(String driverAddress) {
        this.driverAddress = driverAddress;
    }
    public String getDriverMobile() {
        return this.driverMobile;
    }
    
    public void setDriverMobile(String driverMobile) {
        this.driverMobile = driverMobile;
    }
    public String getDriverBloodGroup() {
        return this.driverBloodGroup;
    }
    
    public void setDriverBloodGroup(String driverBloodGroup) {
        this.driverBloodGroup = driverBloodGroup;
    }
    public Date getDriverDateOfJoining() {
        return this.driverDateOfJoining;
    }
    
    public void setDriverDateOfJoining(Date driverDateOfJoining) {
        this.driverDateOfJoining = driverDateOfJoining;
    }
    public String getDriverPic() {
        return this.driverPic;
    }
    
    public void setDriverPic(String driverPic) {
        this.driverPic = driverPic;
    }
    public Date getDriverDateOfAddition() {
        return this.driverDateOfAddition;
    }
    
    public void setDriverDateOfAddition(Date driverDateOfAddition) {
        this.driverDateOfAddition = driverDateOfAddition;
    }
    public Date getDriverTimeOfAddition() {
        return this.driverTimeOfAddition;
    }
    
    public void setDriverTimeOfAddition(Date driverTimeOfAddition) {
        this.driverTimeOfAddition = driverTimeOfAddition;
    }
    public String getDriverLocation() {
        return this.driverLocation;
    }
    
    public void setDriverLocation(String driverLocation) {
        this.driverLocation = driverLocation;
    }
    public String getDriverAddedByPersonName() {
        return this.driverAddedByPersonName;
    }
    
    public void setDriverAddedByPersonName(String driverAddedByPersonName) {
        this.driverAddedByPersonName = driverAddedByPersonName;
    }
    public String getDriverAddedWithRight() {
        return this.driverAddedWithRight;
    }
    
    public void setDriverAddedWithRight(String driverAddedWithRight) {
        this.driverAddedWithRight = driverAddedWithRight;
    }
    public String getRawField1() {
        return this.rawField1;
    }
    
    public void setRawField1(String rawField1) {
        this.rawField1 = rawField1;
    }
    public String getRawField2() {
        return this.rawField2;
    }
    
    public void setRawField2(String rawField2) {
        this.rawField2 = rawField2;
    }
    public String getRawField3() {
        return this.rawField3;
    }
    
    public void setRawField3(String rawField3) {
        this.rawField3 = rawField3;
    }
    public String getRawField4() {
        return this.rawField4;
    }
    
    public void setRawField4(String rawField4) {
        this.rawField4 = rawField4;
    }
    public String getRawField5() {
        return this.rawField5;
    }
    
    public void setRawField5(String rawField5) {
        this.rawField5 = rawField5;
    }
    public String getRawField6() {
        return this.rawField6;
    }
    
    public void setRawField6(String rawField6) {
        this.rawField6 = rawField6;
    }




}


