package com.JD.Master.Hibernate.config;
// Generated Jan 10, 2015 5:29:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Productmaster generated by hbm2java
 */
public class Productmaster  implements java.io.Serializable {


     private Integer id;
     private String productName;
     private Integer productSize;
     private String productMeasurement;
     private Date productDateOfAddition;
     private Date productTimeOfAddition;
     private String productLocation;
     private String productAddedByPersonName;
     private String productAddedWithRight;
     private String rawField1;
     private String rawField2;
     private String rawField3;
     private String rawField4;
     private String rawField5;
     private String rawField6;

    public Productmaster() {
    }

    public Productmaster(String productName, Integer productSize, String productMeasurement, Date productDateOfAddition, Date productTimeOfAddition, String productLocation, String productAddedByPersonName, String productAddedWithRight, String rawField1, String rawField2, String rawField3, String rawField4, String rawField5, String rawField6) {
       this.productName = productName;
       this.productSize = productSize;
       this.productMeasurement = productMeasurement;
       this.productDateOfAddition = productDateOfAddition;
       this.productTimeOfAddition = productTimeOfAddition;
       this.productLocation = productLocation;
       this.productAddedByPersonName = productAddedByPersonName;
       this.productAddedWithRight = productAddedWithRight;
       this.rawField1 = rawField1;
       this.rawField2 = rawField2;
       this.rawField3 = rawField3;
       this.rawField4 = rawField4;
       this.rawField5 = rawField5;
       this.rawField6 = rawField6;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Integer getProductSize() {
        return this.productSize;
    }
    
    public void setProductSize(Integer productSize) {
        this.productSize = productSize;
    }
    public String getProductMeasurement() {
        return this.productMeasurement;
    }
    
    public void setProductMeasurement(String productMeasurement) {
        this.productMeasurement = productMeasurement;
    }
    public Date getProductDateOfAddition() {
        return this.productDateOfAddition;
    }
    
    public void setProductDateOfAddition(Date productDateOfAddition) {
        this.productDateOfAddition = productDateOfAddition;
    }
    public Date getProductTimeOfAddition() {
        return this.productTimeOfAddition;
    }
    
    public void setProductTimeOfAddition(Date productTimeOfAddition) {
        this.productTimeOfAddition = productTimeOfAddition;
    }
    public String getProductLocation() {
        return this.productLocation;
    }
    
    public void setProductLocation(String productLocation) {
        this.productLocation = productLocation;
    }
    public String getProductAddedByPersonName() {
        return this.productAddedByPersonName;
    }
    
    public void setProductAddedByPersonName(String productAddedByPersonName) {
        this.productAddedByPersonName = productAddedByPersonName;
    }
    public String getProductAddedWithRight() {
        return this.productAddedWithRight;
    }
    
    public void setProductAddedWithRight(String productAddedWithRight) {
        this.productAddedWithRight = productAddedWithRight;
    }
    public String getRawField1() {
        return this.rawField1;
    }
    
    public void setRawField1(String rawField1) {
        this.rawField1 = rawField1;
    }
    public String getRawField2() {
        return this.rawField2;
    }
    
    public void setRawField2(String rawField2) {
        this.rawField2 = rawField2;
    }
    public String getRawField3() {
        return this.rawField3;
    }
    
    public void setRawField3(String rawField3) {
        this.rawField3 = rawField3;
    }
    public String getRawField4() {
        return this.rawField4;
    }
    
    public void setRawField4(String rawField4) {
        this.rawField4 = rawField4;
    }
    public String getRawField5() {
        return this.rawField5;
    }
    
    public void setRawField5(String rawField5) {
        this.rawField5 = rawField5;
    }
    public String getRawField6() {
        return this.rawField6;
    }
    
    public void setRawField6(String rawField6) {
        this.rawField6 = rawField6;
    }




}


