/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.JD.Notification.Form;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Yogesh
 */
public class Notification extends javax.swing.JFrame {

    SessionFactory init_SessionFactory=com.JD.StaticData.Static_DATA.init_SessionFactory;
    javax.swing.table.DefaultTableModel servicing_DefaultModel;
    
    /**
     * Creates new form Notification
     */
    public Notification() {
        initComponents();
        com.JD.StaticData.Static_DATA.Notification_status_Table=Notification_status_Table;
        com.JD.StaticData.Static_DATA.notification_running_Lable=notification_running_Lable;   
        com.JD.StaticData.Static_DATA.notification=this;
        com.JD.StaticData.Static_DATA.notification_fuelQuantity_Lable=notification_fuelQuantity_Lable;
        servicing_DefaultModel=(DefaultTableModel) servicing_Table.getModel();
        resetServicingTable();
        com.JD.StaticData.Static_DATA.purchaseDiesel_Form.setCurrentDieselLog(0.0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void resetServicingTable(){
        int j=-1;
        for (int i = servicing_DefaultModel.getRowCount() - 1; i >= 0; i--) {
            servicing_DefaultModel.removeRow(i);
        }
        Session session=init_SessionFactory.openSession();
        Criteria cr = session.createCriteria(com.JD.Master.Hibernate.config.Machinemaster.class);
        cr.add(Restrictions.eq("machineServicingFlag", "TRUE"));
        List results = cr.list();
        for (Object object : results) {
            com.JD.Master.Hibernate.config.Machinemaster m=(com.JD.Master.Hibernate.config.Machinemaster)object;
            ++j;
            servicing_DefaultModel.insertRow(j,new Object[]{m.getMachineNumber(),m.getMachineName(),m.getMachineCurrentReading()});
        }       
        com.JD.StaticData.Static_DATA.readyMachine_Lable.setText("  + "+results.size()+" Machine Ready For Servicing   ");
        localServicing_Lable.setText(" + "+results.size()+" Machine");
        session.close();
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notification_Panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        notification_fuelQuantity_Lable = new javax.swing.JLabel();
        notification_running_Lable = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Notification_status_Table = new javax.swing.JTable();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        servicing_Table = new javax.swing.JTable();
        localServicing_Lable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        notification_Panel.setBackground(new java.awt.Color(255, 102, 51));

        jLabel6.setText("1: Current Quantity Of Diesel :");

        jLabel7.setText("2: Machine Already Running List :");

        notification_fuelQuantity_Lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/purched.png"))); // NOI18N
        notification_fuelQuantity_Lable.setText(" +134.99 LTR ");
        notification_fuelQuantity_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        notification_fuelQuantity_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notification_fuelQuantity_Lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notification_fuelQuantity_LableMouseClicked(evt);
            }
        });

        notification_running_Lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/running.png"))); // NOI18N
        notification_running_Lable.setText("  + 023 Machine Running");
        notification_running_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        notification_running_Lable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notification_running_Lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notification_running_LableMouseClicked(evt);
            }
        });

        Notification_status_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Machine Number", "Machine Name", "Start Date", "Start Time", "Current Reading", "Fuel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Notification_status_Table);

        jLabel1.setText("3: Machine Servicing Log ");

        servicing_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Machine Number", "Machine Name", "Current"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(servicing_Table);

        localServicing_Lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JD/Home/servi.png"))); // NOI18N
        localServicing_Lable.setText(" + 012 Machine");
        localServicing_Lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));

        javax.swing.GroupLayout notification_PanelLayout = new javax.swing.GroupLayout(notification_Panel);
        notification_Panel.setLayout(notification_PanelLayout);
        notification_PanelLayout.setHorizontalGroup(
            notification_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator7)
            .addComponent(jSeparator1)
            .addGroup(notification_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(notification_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notification_PanelLayout.createSequentialGroup()
                        .addGroup(notification_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(localServicing_Lable, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane4))
                    .addGroup(notification_PanelLayout.createSequentialGroup()
                        .addGroup(notification_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(notification_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(75, 75, 75)
                                .addComponent(notification_fuelQuantity_Lable))
                            .addGroup(notification_PanelLayout.createSequentialGroup()
                                .addGroup(notification_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(notification_running_Lable, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        notification_PanelLayout.setVerticalGroup(
            notification_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notification_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(notification_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(notification_fuelQuantity_Lable))
                .addGap(14, 14, 14)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(notification_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notification_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notification_running_Lable, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(notification_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notification_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(localServicing_Lable, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notification_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notification_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notification_fuelQuantity_LableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notification_fuelQuantity_LableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_notification_fuelQuantity_LableMouseClicked

    private void notification_running_LableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notification_running_LableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_notification_running_LableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Notification().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Notification_status_Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel localServicing_Lable;
    public javax.swing.JPanel notification_Panel;
    public javax.swing.JLabel notification_fuelQuantity_Lable;
    private javax.swing.JLabel notification_running_Lable;
    private javax.swing.JTable servicing_Table;
    // End of variables declaration//GEN-END:variables
}
