/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.JD.Search;

import com.JD.DatePicker.DatePicker;
import com.JD.Test.*;
import com.JD.Master.Forms.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 *
 * @author Yogesh
 */
public class PurchaseDiesel_Search extends javax.swing.JFrame {

    String oilCompanyNameTemp = "";
    String personNameTemp = "";
    //---Load Date Panel---//
    com.JD.DatePicker.DatePicker datePicker = new DatePicker();
    JDatePickerImpl date1 = datePicker.getDateObjectUp();
    JDatePickerImpl date2 = datePicker.getDateObjectDown();
    List queryList = new ArrayList();
    javax.swing.table.DefaultTableModel defaultTableModel;
    SessionFactory search_SessionFactory = com.JD.StaticData.Static_DATA.init_SessionFactory;
    //---Load Date Panel---//

    /**
     * Creates new form Party_MasterForm
     */
    public PurchaseDiesel_Search() {
        initComponents();
        //----Load Calender----//
        date1.setBounds(17, 51, 200, 50);
        date1.setBackground(Color.yellow);
        date2.setBackground(Color.yellow);
        date_panel.add(date1);
        date_panel.add(date2);
        date2.setBounds(17, 102, 200, 40);
        //----Load Calender----//
        defaultTableModel = (DefaultTableModel) diesel_Table.getModel();
        //----Fill Static Data---------//
        com.JD.StaticData.Static_DATA.purchaseSearch_company_ComboBox = purchaseSearch_company_ComboBox;
        com.JD.StaticData.Static_DATA.purchase_Perseon_Search_ComboBox = purchase_Perseon_Search_ComboBox;
        //----Fill Static Data---------//

        Session session = search_SessionFactory.openSession();
        Query q = session.createQuery("from com.Hibernate.diesel.config.Purchasediesel");
        for (Object object : q.list()) {
            com.Hibernate.diesel.config.Purchasediesel p = (com.Hibernate.diesel.config.Purchasediesel) object;
            if (oilCompanyNameTemp.contains(p.getOilCompanyName())) {
            } else {
                oilCompanyNameTemp += "##" + p.getOilCompanyName();
                com.JD.StaticData.Static_DATA.purchaseSearch_company_ComboBox.addItem(p.getOilCompanyName());

            }
            if (personNameTemp.contains(p.getPersonPresentName())) {
            } else {
                personNameTemp += "##" + p.getPersonPresentName();
                com.JD.StaticData.Static_DATA.purchase_Perseon_Search_ComboBox.addItem(p.getPersonPresentName());
            }
        }

        session.close();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchase_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diesel_Table = new javax.swing.JTable();
        date_panel = new javax.swing.JPanel();
        betwee_CheackBox = new javax.swing.JCheckBox();
        equal_CheackBox = new javax.swing.JCheckBox();
        early_CheackBox = new javax.swing.JCheckBox();
        late_CheackBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clear_CheackBox = new javax.swing.JCheckBox();
        purchaseSearch_company_ComboBox = new javax.swing.JComboBox();
        purchase_Perseon_Search_ComboBox = new javax.swing.JComboBox();
        search_Button = new javax.swing.JButton();
        export_Button = new javax.swing.JButton();
        print_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        purchase_Panel.setBackground(new java.awt.Color(255, 255, 51));

        diesel_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last", "Received", "Present", "Person Name", "Oil Company", "Slip No", "DOA", "TOA", "Added By", "Right", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(diesel_Table);

        date_panel.setBackground(new java.awt.Color(255, 255, 51));
        date_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true));

        betwee_CheackBox.setBackground(new java.awt.Color(255, 255, 51));
        betwee_CheackBox.setText("Between");
        betwee_CheackBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        betwee_CheackBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betwee_CheackBoxActionPerformed(evt);
            }
        });

        equal_CheackBox.setBackground(new java.awt.Color(255, 255, 51));
        equal_CheackBox.setText("Equal");
        equal_CheackBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        equal_CheackBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_CheackBoxActionPerformed(evt);
            }
        });

        early_CheackBox.setBackground(new java.awt.Color(255, 255, 51));
        early_CheackBox.setText("Early");
        early_CheackBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        early_CheackBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                early_CheackBoxActionPerformed(evt);
            }
        });

        late_CheackBox.setBackground(new java.awt.Color(255, 255, 51));
        late_CheackBox.setText("Late");
        late_CheackBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        late_CheackBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                late_CheackBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("From:");

        jLabel3.setText("To:");

        clear_CheackBox.setBackground(new java.awt.Color(255, 255, 51));
        clear_CheackBox.setText("Clear");

        javax.swing.GroupLayout date_panelLayout = new javax.swing.GroupLayout(date_panel);
        date_panel.setLayout(date_panelLayout);
        date_panelLayout.setHorizontalGroup(
            date_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(date_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(date_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(date_panelLayout.createSequentialGroup()
                        .addComponent(betwee_CheackBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equal_CheackBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(early_CheackBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(late_CheackBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear_CheackBox))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        date_panelLayout.setVerticalGroup(
            date_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(date_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(date_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betwee_CheackBox)
                    .addComponent(equal_CheackBox)
                    .addComponent(early_CheackBox)
                    .addComponent(late_CheackBox)
                    .addComponent(clear_CheackBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        purchaseSearch_company_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oil Company Name" }));

        purchase_Perseon_Search_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Person Persent" }));

        search_Button.setText("Search");
        search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_ButtonActionPerformed(evt);
            }
        });

        export_Button.setText("Export To Excel");

        print_Button.setText("Print");

        javax.swing.GroupLayout purchase_PanelLayout = new javax.swing.GroupLayout(purchase_Panel);
        purchase_Panel.setLayout(purchase_PanelLayout);
        purchase_PanelLayout.setHorizontalGroup(
            purchase_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1263, Short.MAX_VALUE)
            .addGroup(purchase_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(purchase_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(purchase_PanelLayout.createSequentialGroup()
                        .addComponent(search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(export_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(print_Button))
                    .addComponent(purchase_Perseon_Search_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchaseSearch_company_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        purchase_PanelLayout.setVerticalGroup(
            purchase_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchase_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(purchase_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(purchase_PanelLayout.createSequentialGroup()
                        .addComponent(purchaseSearch_company_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(purchase_Perseon_Search_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(purchase_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_Button)
                            .addComponent(export_Button)
                            .addComponent(print_Button))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchase_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchase_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void betwee_CheackBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betwee_CheackBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betwee_CheackBoxActionPerformed

    private void equal_CheackBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_CheackBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equal_CheackBoxActionPerformed

    private void early_CheackBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_early_CheackBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_early_CheackBoxActionPerformed

    private void late_CheackBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_late_CheackBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_late_CheackBoxActionPerformed

    private void search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseDiesel_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseDiesel_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseDiesel_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseDiesel_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PurchaseDiesel_Search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox betwee_CheackBox;
    private javax.swing.JCheckBox clear_CheackBox;
    private javax.swing.JPanel date_panel;
    private javax.swing.JTable diesel_Table;
    private javax.swing.JCheckBox early_CheackBox;
    private javax.swing.JCheckBox equal_CheackBox;
    private javax.swing.JButton export_Button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox late_CheackBox;
    private javax.swing.JButton print_Button;
    private javax.swing.JComboBox purchaseSearch_company_ComboBox;
    public javax.swing.JPanel purchase_Panel;
    private javax.swing.JComboBox purchase_Perseon_Search_ComboBox;
    private javax.swing.JButton search_Button;
    // End of variables declaration//GEN-END:variables
}
