package com.JD.Machine.StartStop.Hibernate.config;
// Generated Jan 10, 2015 3:19:22 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Machinestartstop generated by hbm2java
 */
public class Machinestartstop  implements java.io.Serializable {


     private Integer id;
     private String machineName;
     private Date startDay;
     private Date stopDay;
     private Date start;
     private Date stop;
     private String totalTime;
     private Integer startReading;
     private Integer stopReading;
     private Integer totalReading;
     private String operatorName;
     private Integer numberOfTrip;
     private Double average;
     private String remark;
     private Date dateOfAddition;
     private Date timeOfAddition;
     private String location;
     private String addedByPersonName;
     private String addedWithRight;
     private String rawField1;
     private String rawField2;
     private String rawField3;
     private String rawField4;
     private String rawField5;
     private String rawField6;

    public Machinestartstop() {
    }

    public Machinestartstop(String machineName, Date startDay, Date stopDay, Date start, Date stop, String totalTime, Integer startReading, Integer stopReading, Integer totalReading, String operatorName, Integer numberOfTrip, Double average, String remark, Date dateOfAddition, Date timeOfAddition, String location, String addedByPersonName, String addedWithRight, String rawField1, String rawField2, String rawField3, String rawField4, String rawField5, String rawField6) {
       this.machineName = machineName;
       this.startDay = startDay;
       this.stopDay = stopDay;
       this.start = start;
       this.stop = stop;
       this.totalTime = totalTime;
       this.startReading = startReading;
       this.stopReading = stopReading;
       this.totalReading = totalReading;
       this.operatorName = operatorName;
       this.numberOfTrip = numberOfTrip;
       this.average = average;
       this.remark = remark;
       this.dateOfAddition = dateOfAddition;
       this.timeOfAddition = timeOfAddition;
       this.location = location;
       this.addedByPersonName = addedByPersonName;
       this.addedWithRight = addedWithRight;
       this.rawField1 = rawField1;
       this.rawField2 = rawField2;
       this.rawField3 = rawField3;
       this.rawField4 = rawField4;
       this.rawField5 = rawField5;
       this.rawField6 = rawField6;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMachineName() {
        return this.machineName;
    }
    
    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }
    public Date getStartDay() {
        return this.startDay;
    }
    
    public void setStartDay(Date startDay) {
        this.startDay = startDay;
    }
    public Date getStopDay() {
        return this.stopDay;
    }
    
    public void setStopDay(Date stopDay) {
        this.stopDay = stopDay;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getStop() {
        return this.stop;
    }
    
    public void setStop(Date stop) {
        this.stop = stop;
    }
    public String getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(String totalTime) {
        this.totalTime = totalTime;
    }
    public Integer getStartReading() {
        return this.startReading;
    }
    
    public void setStartReading(Integer startReading) {
        this.startReading = startReading;
    }
    public Integer getStopReading() {
        return this.stopReading;
    }
    
    public void setStopReading(Integer stopReading) {
        this.stopReading = stopReading;
    }
    public Integer getTotalReading() {
        return this.totalReading;
    }
    
    public void setTotalReading(Integer totalReading) {
        this.totalReading = totalReading;
    }
    public String getOperatorName() {
        return this.operatorName;
    }
    
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }
    public Integer getNumberOfTrip() {
        return this.numberOfTrip;
    }
    
    public void setNumberOfTrip(Integer numberOfTrip) {
        this.numberOfTrip = numberOfTrip;
    }
    public Double getAverage() {
        return this.average;
    }
    
    public void setAverage(Double average) {
        this.average = average;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getDateOfAddition() {
        return this.dateOfAddition;
    }
    
    public void setDateOfAddition(Date dateOfAddition) {
        this.dateOfAddition = dateOfAddition;
    }
    public Date getTimeOfAddition() {
        return this.timeOfAddition;
    }
    
    public void setTimeOfAddition(Date timeOfAddition) {
        this.timeOfAddition = timeOfAddition;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getAddedByPersonName() {
        return this.addedByPersonName;
    }
    
    public void setAddedByPersonName(String addedByPersonName) {
        this.addedByPersonName = addedByPersonName;
    }
    public String getAddedWithRight() {
        return this.addedWithRight;
    }
    
    public void setAddedWithRight(String addedWithRight) {
        this.addedWithRight = addedWithRight;
    }
    public String getRawField1() {
        return this.rawField1;
    }
    
    public void setRawField1(String rawField1) {
        this.rawField1 = rawField1;
    }
    public String getRawField2() {
        return this.rawField2;
    }
    
    public void setRawField2(String rawField2) {
        this.rawField2 = rawField2;
    }
    public String getRawField3() {
        return this.rawField3;
    }
    
    public void setRawField3(String rawField3) {
        this.rawField3 = rawField3;
    }
    public String getRawField4() {
        return this.rawField4;
    }
    
    public void setRawField4(String rawField4) {
        this.rawField4 = rawField4;
    }
    public String getRawField5() {
        return this.rawField5;
    }
    
    public void setRawField5(String rawField5) {
        this.rawField5 = rawField5;
    }
    public String getRawField6() {
        return this.rawField6;
    }
    
    public void setRawField6(String rawField6) {
        this.rawField6 = rawField6;
    }




}


